name:                escli
version:             0.1.0.0
github:              "DaveCTurner/escli"
license:             BSD3
author:              "David Turner"
maintainer:          "dave.c.turner@gmail.com"
copyright:           "2018-2023 David Turner"

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- attoparsec
- bytestring
- conduit
- conduit-extra
- connection
- data-default-class
- directory
- filepath
- http-client
- http-client-tls
- http-media
- http-types
- iso8601-time
- mtl
- network-uri
- optparse-applicative
- process
- text
- time
- tls
- x509-store
- x509-system
- x509-validation
- MissingH

library:
  source-dirs: lib
  exposed-modules:
  - Cloud.Responses
  - Config
  - Config.Parser
  - Config.File
  - CredentialsUtils
  - ESCommand
  - HttpClient
  ghc-options:
  - -Wall -Werror

executables:
  escli:
    main:                Main.hs
    source-dirs:         src
    dependencies:
      - escli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Werror

tests:
  escli-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - base
      - escli
      - hspec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Werror
