name:                escli
version:             0.1.0.0
github:              "DaveCTurner/escli"
license:             BSD3
author:              "David Turner"
maintainer:          "dave.c.turner@gmail.com"
copyright:           "2018 Author name here"

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- attoparsec
- bytestring
- conduit
- conduit-extra
- connection
- data-default-class
- directory
- filepath
- http-client
- http-client-tls
- http-media
- http-types
- iso8601-time
- mtl
- network-uri
- optparse-applicative
- text
- time
- tls
- x509-store
- x509-system
- x509-validation

executables:
  escli:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Werror
    other-modules:
    - Config
    - ESCommand
